import streamlit as st
from transformers import pipeline
from langchain.text_splitter import CharacterTextSplitter
import io
import re

# Choose a suitable Hugging Face model for question answering
model_name = "impira/layoutlm-document-qa"  # Example model, replace with your choice

@st.cache_resource
def process_document(uploaded_file):
    """
    Reads text content from uploaded PDF or DOCX using appropriate libraries.

    Args:
        uploaded_file (streamlit.uploadedfile.UploadedFile): The uploaded file.

    Returns:
        list: The extracted paragraphs from the file.
    """
    if uploaded_file.type == "application/pdf":
        import PyPDF2

        with io.BytesIO(uploaded_file.read()) as file_object:
            reader = PyPDF2.PdfReader(file_object)

            paragraphs = []
            for page in reader.pages:
                paragraphs.append(page.extract_text())

            return paragraphs

    elif uploaded_file.type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
        import docx2txt

    text_bytes = uploaded_file.read()
    text_io = io.BytesIO(text_bytes)
    text = docx2txt.process(text_io)
    paragraphs = re.split(r'\n\s*\n', text)
    return paragraphs

    #else:
    #st.error("Unsupported file type. Please upload a PDF or DOCX document.")
        #return []



def answer_question(question, paragraphs):
    """
    Sends the question and processed text to the Hugging Face model for answer generation.

    Args:
        question (str): The user's question about the document.
        paragraphs (list): List of paragraphs extracted from the document.

    Returns:
        str: The answer generated by the Hugging Face model.
    """
    context = "\n".join(paragraphs)

    qa_pipeline = pipeline("question-answering", model=model_name)
    answer = qa_pipeline(question=question, context=context)["answer"]
    return answer

st.set_page_config(page_title="Document Reader & Questioner", layout="wide")

st.title("Read and Ask Questions about Your Documents")
uploaded_file = st.file_uploader("Choose a document:", type=["pdf", "docx"])

if uploaded_file is not None:
    with st.spinner("Processing document..."):
        paragraphs = process_document(uploaded_file)

    if paragraphs:
        question = st.text_input("Ask a question about the document:")

        if question:
            answer = answer_question(question, paragraphs)
            st.success("**Answer:**")
            st.write(answer)
